root: true
env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - standard
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:playwright/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
plugins:
  - '@typescript-eslint'
rules:
  semi:
    - error
    - always
  comma-dangle:
    - error
    - always-multiline
